name: Upload FastApi-Mail Package

on:
  release:
    types: [created]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install poetry
    - run: poetry build
    - run: poetry config http-basic.pypi  ${{ secrets.PYPI_USERNAME }}  ${{ secrets.PYPI_PASSWORD }}
    - run: poetry publish 
